name: Debug Single Cypress Spec with Allure

on:
  # push: # Trigger the workflow on push events
  #   branches:
  #     - main # Specify the branch(es) to trigger the workflow
  #     - develop # Add other branches if needed
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  single-spec-debug:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      EXPECTED_FROM: ${{ secrets.EXPECTED_FROM }}
      TERM: xterm

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run ONLY document.cy.js
        run: |
          rm -rf allure-results allure-report
          mkdir -p allure-results
          npx cypress run \
            --spec "cypress/e2e/auth/signup.cy.js" \
            --browser chrome --headless

      - name: Debug - Count Allure JSON Files
        run: |
          ls -l allure-results/*.json | wc -l

